services:
  - type: web
    name: pathforge
    env: node
    plan: free
    buildCommand: npm install && npm install --prefix backend && npm install --prefix frontend && npm run build --prefix frontend
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.10.0
      - key: npm_config_production
        value: false
      - key: MONGO_URI
        sync: false
        placeholder: "Your MongoDB Connection URI (e.g. mongodb+srv://...)"
      - key: JWT_SECRET
        generateValue: true
